var dataC =[
           		{name: '阿富汗', value: 1800, suppliers:['VDF','TEL','CC'], testPO:300, businessPO:600, onNetPO:600},
                {name: '安哥拉', value: 1600, suppliers:['VDF','TEL','CC'], testPO:300, businessPO:600, onNetPO:600},
                {name: '阿尔巴尼亚', value: 1600, suppliers:['VDF','TEL','CC'], testPO:300, businessPO:600, onNetPO:600},
                {name: '阿联酋', value: 1600, suppliers:['VDF','TEL','CC'], testPO:300, businessPO:600, onNetPO:600},
                {name: '阿根廷', value: 1600, suppliers:['VDF','TEL','CC'], testPO:300, businessPO:600, onNetPO:600},
                {name: '亚美尼亚', value: 1600, suppliers:['VDF','TEL','CC'], testPO:300, businessPO:600, onNetPO:600},
                {name: '法属南部领地', value: 1600, suppliers:['VDF','TEL','CC'], testPO:300, businessPO:600, onNetPO:600},
                {name: '澳大利亚', value: 1600, suppliers:['VDF','TEL','CC'], testPO:300, businessPO:600, onNetPO:600},
                {name: '奥地利', value: 1600, suppliers:['VDF','TEL','CC'], testPO:300, businessPO:600, onNetPO:600},
                {name: '美属萨摩亚群岛', value: 1600, suppliers:['VDF','TEL','CC'], testPO:300, businessPO:600, onNetPO:600},
                {name: '阿塞拜疆', value: 1600, suppliers:['VDF','TEL','CC'], testPO:300, businessPO:600, onNetPO:600},
                {name: '布隆迪', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '比利时', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '贝宁', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '布基纳法索', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '孟加拉', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '保加利亚', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '巴哈马', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '波黑', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '白俄罗斯', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '伯利兹', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '百慕大群岛', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '玻利维亚', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '巴西', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '文莱', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '不丹', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '博茨瓦纳', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '中非共和国', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '加拿大', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '瑞士', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '智利', value: 1200, suppliers:['VDF','CC'], testPO:200, businessPO:500, onNetPO:500},
                {name: '中国', value: -2},
                {name: '象牙海岸', value: 0},
                {name: '喀麦隆', value: 0},
                {name: '民主刚果', value: 0},
                {name: '刚果共和国', value: 0},
                {name: '哥伦比亚', value: 0},
                {name: '哥斯达黎加', value: 0},
                {name: '古巴', value: 0},
                {name: '北塞浦路斯', value: 0},
                {name: '塞浦路斯', value: 0},
                {name: '捷克', value: 0},
                {name: '德国', value: 0},
                {name: '吉布提', value: 0},
                {name: '丹麦', value: 0},
                {name: '多米尼加', value: 0},
                {name: '阿尔及利亚', value: 0},
                {name: '厄瓜多尔', value: 0},
                {name: '埃及', value: 0},
                {name: '厄立特里亚', value: 0},
                {name: '西班牙', value: 0},
                {name: '爱沙尼亚', value: 0},
                {name: '埃塞俄比亚', value: 0},
                {name: '芬兰', value: -1},
                {name: '斐济', value: -1},
                {name: '福克兰群岛', value: -1},
                {name: '法国', value: -1},
                {name: '加蓬', value: -1},
                {name: '英国', value: -2},
                {name: '格鲁吉亚', value: -1},
                {name: '加纳', value: -1},
                {name: '几内亚', value: -1},
                {name: '冈比亚', value: -1},
                {name: '几内亚比绍', value: -1},
                {name: '赤道几内亚', value: -1},
                {name: '希腊', value: -1},
                {name: '格林兰', value: -1},
                {name: '危地马拉', value: -1},
                {name: '法属圭亚那', value: -1},
                {name: '圭亚那', value: -1},
                {name: '洪都拉斯', value: -1},
                {name: '克罗地亚', value: -1},
                {name: '海地', value: -1},
                {name: '匈牙利', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '印度尼西亚', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '印度', value: 2000, suppliers:['VDF','TEL','CC'], testPO:300, businessPO:600, onNetPO:600},
                {name: '爱尔兰', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '伊朗', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '伊拉克', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '冰岛', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '以色列', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '意大利', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '牙买加', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '约旦', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '日本', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '哈萨克斯坦', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '肯尼亚', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '吉尔吉斯斯坦', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '柬埔寨', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '韩国', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '科索沃', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '科威特', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '老挝', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '黎巴嫩', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '利比里亚', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '利比亚', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '斯里兰卡', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '莱索托', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '立陶宛', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '卢森堡', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '拉脱维亚', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '摩洛哥', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '摩尔多瓦', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '马达加斯加', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '墨西哥', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '马其顿', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '马里', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '缅甸', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '黑山', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '蒙古', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '莫桑比克', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '毛里塔尼亚', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '马拉维', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '马来西亚', value: 800, suppliers:['VDF'], testPO:100, businessPO:300, onNetPO:300},
                {name: '纳米比亚', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '新喀里多尼亚', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '尼日尔', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '尼日利亚', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '尼加拉瓜', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '荷兰', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '挪威', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '尼泊尔', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '新西兰', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '阿曼', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '巴基斯坦', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '巴拿马', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '秘鲁', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '菲律宾', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '巴布亚新几内亚', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '波兰', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '波多黎各', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '朝鲜', value: -2},
                {name: '葡萄牙', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '巴拉圭', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '卡塔尔', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '罗马尼亚', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '俄罗斯', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '卢旺达', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '西撒哈拉', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '沙特阿拉伯', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '苏丹', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '南苏丹', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '塞内加尔', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '所罗门群岛', value: 300, suppliers:['CC'], testPO:100, businessPO:100, onNetPO:100},
                {name: '塞拉利昂', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '萨尔瓦多', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '索马里兰', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '索马里', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '塞尔维亚共和国', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '苏里南', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '斯洛伐克', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '斯洛文尼亚', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '瑞典', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '斯威士兰', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '叙利亚', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '乍得', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '多哥', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '泰国', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '塔吉克斯坦', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '土库曼斯坦', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '东帝汶', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '特立尼达和多巴哥', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '突尼斯', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '土耳其', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '坦桑尼亚', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '乌干达', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '乌克兰', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '乌拉圭', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '美国', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '乌兹别克斯坦', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '委内瑞拉', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '越南', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '瓦努阿图', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '约旦河西岸', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '也门', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '南非', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '赞比亚', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10},
                {name: '津巴布韦', value: 30, suppliers:['CC'], testPO:10, businessPO:10, onNetPO:10}
                ];